In [23]:
import numpy as np

!mkdir DATA
!mkdir DATA_b

mkdir: cannot create directory ‘DATA’: File exists


### Data, first kind

In [116]:
# random seed for reproducibility
np.random.seed(12345)
print("random numbers from seed 12345:",np.random.random(4))
    
    
# size of dataset
N=10000
# number of block for one-hot encoding
G=5
# size of a block
A=6
# size of a stretch of 1's in a block
A0=4
# the reminder
A1=A-A0
# size of each data point
L=G*A
#  
# Noise: probability q to change category
q=0.1
print(f"L={L}, A={A}, G={G}")

x,y = np.zeros((N,L)).astype(int), np.zeros(N).astype(int)

for n in range(N):
    # kind of the first slot
    k = np.random.randint(0,2)
    # label
    y[n] = k
    i0=0
    for g in range(G):
        # normal choice
        j = i0 + k*A1
        x[n][j:j+A0] = 1
        for j in range(i0,i0+A):
            if np.random.random()<q:
                x[n][j] = 1-x[n][j]
        
        if(n<3): print(f"k={k}, g={g}, i0={i0}")
        i0= i0 + A
        k = 1 - k
                
    if(n<11): print(x[n],y[n])

print("...")
    
np.savetxt('DATA/x_RBM_q'+str(q)+'.dat',x,delimiter=" ",fmt="%d")
np.savetxt('DATA/y_RBM_q'+str(q)+'.dat',y,fmt="%d")

random numbers from seed 12345: [0.92961609 0.31637555 0.18391881 0.20456028]
L=30, A=6, G=5
k=1, g=0, i0=0
k=0, g=1, i0=6
k=1, g=2, i0=12
k=0, g=3, i0=18
k=1, g=4, i0=24
[0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1] 1
k=0, g=0, i0=0
k=1, g=1, i0=6
k=0, g=2, i0=12
k=1, g=3, i0=18
k=0, g=4, i0=24
[1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0] 0
k=1, g=0, i0=0
k=0, g=1, i0=6
k=1, g=2, i0=12
k=0, g=3, i0=18
k=1, g=4, i0=24
[0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1] 1
[0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 1 1] 1
[1 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0] 0
[0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0] 1
[1 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 1 1] 1
[0 0 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 1 1] 1
[0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1] 1
[1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0] 0
[1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [117]:
from IPython.display import display_html 
import pandas as pd

def is_one(cell_value):
    color0 = 'background-color: blue; color: white'
    color1 = 'background-color: cyan;'
    if type(cell_value) in [float, int]:
        if cell_value == 1:
            return color1
    return color0

N1=12
df0 = pd.DataFrame(x[:N1])
df0s = df0.style.set_table_attributes("style='display:inline'")
df0s.applymap(is_one)
sty = [dict(selector="caption",props=[("font-size", "150%")])]
df0s.set_caption('Original').set_table_styles(sty)

display_html(df0s._repr_html_(), raw=True)

df=df0
t=[i for i in range(N1)]
g = pd.Categorical(df[t]).codes # convert groups to indices  
df.style.apply(
    lambda x: ['background-color: {}'.format("#FFCCCC") for i in g], 
    subset=[0,1,2,3,4,5, 12,13,14,15,16,17, 24,25,26,27,28,29 ]
)

Original 
 
 
   
 0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
 11 
 12 
 13 
 14 
 15 
 16 
 17 
 18 
 19 
 20 
 21 
 22 
 23 
 24 
 25 
 26 
 27 
 28 
 29 
 
 
 
 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 
 
 1 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 
 
 2 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 1 
 1 
 1 
 
 
 3 
 0 
 0 
 1 
 0 
 1 
 1 
 1 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 
 
 4 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 0 
 1 
 0 
 0 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 
 
 5 
 0 
 1 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 1 
 1 
 1 
 0 
 
 
 6 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 0 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 
 
 7 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 
 
 8 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 1 
 0 
 0 
 0 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 
 
 9 
 1 
 1 
 1 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 
 
 10 
 1 
 1 
 1 
 1 
 0 
 1 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 
 
 11 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 0 
 0 
 1 
 1 
 1 
 1 
 1 
 1 
 1 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 1 
 1 
 1 
 1 
 1 
 0 
 0

### Data, second kind, with one-hot encoding

In [121]:
# random seed for reproducibility
np.random.seed(12345)
print("random numbers from seed 12345:",np.random.random(4))
    
    
# size of dataset
N=10000
# number of block for one-hot encoding
G=5
# number of categories
A=4
# number of categories of kind 0
A0=int(A/2)
# number of categories of kind 1
A1=A-A0
#
AA=[A0,A1]
# size of each data point
L=G*A
#  
# Noise: probability q to change category
q=0.1
#
a=0.6
print(f"L={L}, A={A}, G={G}")

x,y = np.zeros((N,L)).astype(int), np.zeros(N).astype(int)

for n in range(N):
    # kind of the first slot
    k = np.random.randint(0,2)
    # label
    y[n] = k
    i0=0
    for g in range(G):
        # normal choice
        i = np.random.randint(0,AA[k])
        j = i + i0 + k*A0
        if np.random.random()<q:
            # normal choice
            i = np.random.randint(0,A)
            j = i + i0
        
        if(n<3): print(f"k={k}, g={g}, i0={i0}, i={i}, j={j}, AA[k]={AA[k]}")
        # one-hot encoding
        x[n][ j ] = 1
        i0= i0 + A
        k = 1 - k
                
    if(n<11): print(x[n],y[n])

print("...")
    
np.savetxt('DATA_b/x_RBM_q'+str(q)+'.dat',x,delimiter=" ",fmt="%d")
np.savetxt('DATA_b/y_RBM_q'+str(q)+'.dat',y,fmt="%d")

random numbers from seed 12345: [0.92961609 0.31637555 0.18391881 0.20456028]
L=20, A=4, G=5
k=1, g=0, i0=0, i=0, j=2, AA[k]=2
k=0, g=1, i0=4, i=0, j=4, AA[k]=2
k=1, g=2, i0=8, i=0, j=10, AA[k]=2
k=0, g=3, i0=12, i=1, j=13, AA[k]=2
k=1, g=4, i0=16, i=0, j=18, AA[k]=2
[0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0] 1
k=1, g=0, i0=0, i=0, j=2, AA[k]=2
k=0, g=1, i0=4, i=0, j=4, AA[k]=2
k=1, g=2, i0=8, i=1, j=11, AA[k]=2
k=0, g=3, i0=12, i=0, j=12, AA[k]=2
k=1, g=4, i0=16, i=1, j=19, AA[k]=2
[0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1] 1
k=1, g=0, i0=0, i=0, j=2, AA[k]=2
k=0, g=1, i0=4, i=1, j=5, AA[k]=2
k=1, g=2, i0=8, i=1, j=11, AA[k]=2
k=0, g=3, i0=12, i=1, j=13, AA[k]=2
k=1, g=4, i0=16, i=1, j=19, AA[k]=2
[0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1] 1
[0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0] 0
[0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0] 0
[0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0] 1
[0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0] 1
[0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1] 1
[1 0 0 0 0 0 1 0 0 1 0 0 0 1 0

In [122]:
N1=12
df0 = pd.DataFrame(x[:N1])

df0s = df0.style.set_table_attributes("style='display:inline'")
df0s.applymap(is_one)
sty = [dict(selector="caption",props=[("font-size", "150%")])]
df0s.set_caption('Original').set_table_styles(sty)

display_html(df0s._repr_html_(), raw=True)

df=df0
t=[i for i in range(N1)]
g = pd.Categorical(df[t]).codes # convert groups to indices  
df.style.apply(
    lambda x: ['background-color: {}'.format("#FFCCCC") for i in g], 
    subset=[0,1,2,3, 8,9,10,11, 16,17,18,19 ]
)

Original 
 
 
   
 0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
 11 
 12 
 13 
 14 
 15 
 16 
 17 
 18 
 19 
 
 
 
 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 1 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 2 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 3 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 
 
 4 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 
 
 5 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 6 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 
 
 7 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 0 
 1 
 
 
 8 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 
 
 9 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 10 
 0 
 0 
 1 
 0 
 0 
 1 
 0 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0 
 
 
 11 
 0 
 0 
 0 
 1 
 0 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 1 
 0 
 0 
 0 
 0 
 0 
 1 
 0